/* Fallowborn — bundled total-conversion mod: Westeros, 297 AC (A Song of Ice and Fire).
   Registered into window.FBMODS at load; enable it from the Mods dialog (title screen or menu).
   The data payload below is the mod JSON verbatim — see mods/README.md for the id mapping. */
window.FBMODS = window.FBMODS || [];
window.FBMODS.push({
  id: 'westeros',
  name: 'Westeros — A Song of Ice and Fire',
  desc: 'Total conversion: Westeros in 297 AC, the year before A Game of Thrones. 49 houses, 141 provinces, ASOIAF cultures and faiths, new items and events, and a scripted War of the Five Kings. Start a new life after enabling or disabling — old saves will not fit.',
  data: {
"name": "Westeros — A Song of Ice and Fire (297 AC)",
"balance": { "startYear": 297, "startSeason": 0, "startAge": 16, "wivesByGroup": {}, "aiWarChance": 0.12 },

"bounds": { "lonMin": -14, "lonMax": 14, "latMin": 5, "latMax": 56 },

"land": [
[
  -8.8,10.8, -8.2,10.4, -7.4,9.8, -6.2,9.2, -5.2,8.8, -4.6,8.5,
  -3.8,8.2, -2.6,7.8, -1.2,7.4, 0.2,7.1, 1.6,6.9, 3.0,7.0,
  4.4,7.3, 5.6,7.8, 6.8,8.3, 7.8,8.9, 8.8,9.4, 9.6,10.0,
  9.4,10.8, 8.6,11.4, 8.2,12.0, 7.2,12.3, 6.2,12.4, 5.2,12.6,
  4.6,13.0, 5.4,13.3, 6.4,13.5, 7.4,13.7, 7.9,14.3, 7.5,15.0,
  6.9,15.6, 6.6,16.5, 6.2,17.3, 5.7,18.0, 5.5,18.9, 5.7,19.8,
  6.0,20.5, 6.5,20.9, 7.0,21.3, 6.5,21.8, 6.0,21.9, 5.2,22.1,
  4.4,22.3, 3.6,22.7, 3.1,23.1, 3.0,23.7, 3.4,24.2, 4.0,24.6,
  4.7,24.9, 5.4,25.1, 6.1,25.3, 6.6,25.7, 6.0,26.0, 5.2,26.1,
  4.4,26.2, 3.7,26.1, 3.2,26.4, 3.6,26.8, 4.4,27.0, 5.2,26.9,
  5.9,26.7, 6.5,26.9, 6.8,27.6, 6.7,28.4, 7.3,28.7, 8.5,28.5,
  7.5,29.1, 8.6,29.2, 7.5,29.7, 8.4,30.0, 7.3,30.3, 6.9,30.9,
  6.5,31.5, 5.7,31.6, 4.8,31.8, 4.0,32.1, 2.8,33.2, 3.7,33.9,
  4.4,34.3, 5.2,34.4, 6.0,34.5, 6.9,34.7, 7.6,34.9, 7.0,35.6,
  6.4,36.2, 6.0,37.2, 5.7,38.3, 6.0,39.4, 5.8,40.6, 6.1,41.8,
  6.6,42.6, 7.4,43.3, 7.8,44.0, 7.0,44.6, 6.3,44.9, 5.5,45.3,
  4.9,45.9, 5.3,46.8, 5.6,47.8, 5.1,48.9, 5.3,50.0, 5.9,50.9,
  6.5,51.7, 6.1,52.6, 5.5,53.0, 5.7,54.0, 5.4,55.0, 5.6,56.0,
  -8.0,56.0, -7.6,54.8, -7.9,53.6, -7.0,52.9, -7.3,51.9, -6.5,51.0,
  -6.1,50.2, -6.7,49.3, -6.3,48.3, -6.9,47.5, -6.4,46.7, -5.9,46.2,
  -6.8,45.4, -7.4,44.6, -6.7,43.9, -6.1,43.3, -6.4,42.4, -5.9,41.5,
  -5.2,40.9, -4.4,40.3, -3.5,39.9, -4.2,39.5, -5.3,39.3, -6.1,39.5,
  -6.3,38.9, -5.6,38.5, -4.8,38.2, -4.2,37.5, -3.9,36.7, -4.1,35.9,
  -4.9,35.6, -4.4,34.9, -4.7,34.2, -5.2,33.6, -5.9,33.1, -6.5,32.3,
  -7.0,31.6, -7.5,30.8, -7.9,30.1, -8.3,29.3, -8.5,28.6, -8.2,27.7,
  -8.5,26.9, -8.8,26.1, -8.6,25.3, -9.0,24.4, -9.4,23.5, -9.6,22.5,
  -9.3,21.6, -8.8,21.0, -9.2,20.3, -9.8,19.5, -10.0,18.4, -9.6,17.3,
  -9.8,16.2, -10.1,15.0, -9.9,13.8, -9.5,12.8, -9.2,11.9
],
[ -11.5,10.0, -10.4,10.3, -9.7,9.8, -10.4,9.1, -11.2,9.3 ],
[ -9.9,37.2, -9.0,37.6, -8.4,37.1, -8.3,36.3, -8.8,35.7, -9.6,35.9, -10.0,36.6 ],
[ -7.8,36.2, -7.1,36.1, -7.2,35.6, -7.9,35.7 ],
[ -7.6,37.0, -6.9,37.1, -7.0,36.6, -7.6,36.5 ],
[ -6.8,36.5, -5.9,36.6, -5.6,36.1, -6.4,35.9 ],
[ -6.6,37.5, -5.7,37.5, -5.8,36.9, -6.5,37.0 ],
[ -10.1,31.3, -9.3,31.1, -9.1,30.2, -9.9,30.1 ],
[ -8.6,47.2, -7.6,47.1, -7.5,46.2, -8.5,46.3 ],
[ 6.1,48.3, 7.3,48.5, 8.0,47.7, 7.2,46.9, 6.3,47.3 ],
[ 4.7,32.8, 5.7,32.8, 5.7,32.0, 4.8,32.0 ],
[ 6.3,23.7, 7.1,23.6, 7.2,22.9, 6.4,22.8 ],
[ 7.0,19.5, 7.8,19.3, 8.0,18.1, 7.2,18.1 ],
[ 6.5,16.4, 7.3,16.3, 7.3,15.6, 6.6,15.7 ]
],

"seas": [
[ 1.0,26.4, 2.2,26.5, 2.4,25.7, 1.2,25.6 ],
[ 0.8,46.4, 1.7,46.5, 1.9,45.2, 1.0,45.1 ]
],

"rivers": [
[ -1.6,33.0, -1.1,31.2, -0.4,29.4, 0.6,28.0, 1.8,27.2, 3.2,26.4 ],
[ -4.6,30.2, -3.2,29.4, -1.6,28.6, -0.4,29.4 ],
[ -3.2,32.4, -2.0,30.8, -0.4,29.4 ],
[ -0.6,24.9, 0.8,24.4, 2.0,24.0, 3.0,23.6 ],
[ -0.4,21.4, -2.2,19.4, -4.2,17.4, -6.4,18.6, -8.7,20.7 ],
[ 1.4,40.2, 2.6,37.6, 3.7,34.4 ],
[ 1.4,10.8, 4.4,9.8, 7.8,9.0 ],
[ -2.9,55.0, -3.3,53.0, -4.6,51.0 ],
[ 1.2,46.6, 3.2,45.7, 4.9,46.0 ],
[ -2.9,11.6, -3.9,10.0, -4.6,8.6 ]
],

"titles": {
  "christian":   ["Smallfolk","Freeholder","Landed Knight","Petty Lord","Lord","High Lord","Lord Paramount","King"],
  "christian_f": ["Smallfolk","Freeholder","Gentlewoman","Petty Lady","Lady","High Lady","Lady Paramount","Queen"],
  "pagan":   ["Smallfolk","Crofter","Master","Petty Lord","Lord","High Lord","Warden","King"],
  "pagan_f": ["Smallfolk","Crofter","Mistress","Petty Lady","Lady","High Lady","Warden","Queen"],
  "muslim":   ["Smallfolk","Freeholder","Landed Knight","Petty Lord","Lord","High Lord","Lord Paramount","King"],
  "muslim_f": ["Smallfolk","Freeholder","Gentlewoman","Petty Lady","Lady","High Lady","Lady Paramount","Queen"],
  "jewish": ["Smallfolk","Freeholder","Landed Knight","Petty Lord","Lord","High Lord","Lord Paramount","King"]
},

"religions": {
  "old_gods":    { "name": "The Old Gods", "group": "pagan", "icon": "🌳" },
  "the_seven":   { "name": "The Faith of the Seven", "group": "christian", "icon": "✷" },
  "drowned_god": { "name": "The Drowned God", "group": "pagan", "icon": "🌊" },
  "rhllor":      { "name": "R’hllor, Lord of Light", "group": "jewish", "icon": "🔥" }
},

"cultures": {
"northmen": { "name": "Northman", "dyn": "of_place",
  "male": ["Brandon","Torrhen","Eddard","Rickard","Cregan","Jon","Benjen","Jory","Rodrik","Harwin","Domeric","Hother","Osric","Beron"],
  "female": ["Lyanna","Alys","Barbrey","Dacey","Lyra","Jonelle","Wylla","Berena","Sarra","Arra"] },
"ironborn": { "name": "Ironborn", "dyn": "plain",
  "family": ["Humble","Codd","Netley","Shepherd","Weaver","Kenning","Myre","Sharp"],
  "male": ["Balon","Euron","Victarion","Aeron","Theon","Dagmer","Rodrik","Urron","Dalton","Qarl","Erik","Harmund","Sigfryd","Denys"],
  "female": ["Asha","Gwynesse","Alannys","Esgred","Gysella","Falia","Yara","Sigrin","Helya","Meldred"] },
"rivermen": { "name": "Riverman", "dyn": "of_place",
  "male": ["Edmure","Hoster","Brynden","Walder","Lucas","Marq","Jonos","Clement","Raymun","Oswell","Tristan","Perwyn"],
  "female": ["Catelyn","Lysa","Minisa","Roslin","Amerei","Marissa","Bethany","Zhoe","Alyssa","Carellen"] },
"valemen": { "name": "Valeman", "dyn": "of_place",
  "male": ["Jon","Yohn","Robar","Denys","Nestor","Albar","Harrold","Symond","Gerold","Eustace","Mychel","Andar"],
  "female": ["Anya","Mya","Ysilla","Sharra","Rowena","Jeyne","Myranda","Alayne","Lorra","Waynafred"] },
"westermen": { "name": "Westerman", "dyn": "of_place",
  "male": ["Tywin","Kevan","Tygett","Gerion","Tytos","Stafford","Damion","Lyle","Addam","Roland","Forley","Garrison"],
  "female": ["Genna","Joanna","Darlessa","Myrielle","Cerenna","Shiera","Alysanne","Jeyne","Sybell","Melara"] },
"reachmen": { "name": "Reachman", "dyn": "of_place",
  "male": ["Mace","Loras","Garlan","Willas","Leyton","Baelor","Garth","Gunthor","Moryn","Randyll","Paxter","Vortimer"],
  "female": ["Margaery","Olenna","Alerie","Leonette","Desmera","Janna","Mina","Elinor","Alla","Megga"] },
"stormlander": { "name": "Stormlander", "dyn": "of_place",
  "male": ["Davos","Beric","Bryce","Gulian","Ronnet","Selwyn","Cortnay","Lester","Andrew","Balon","Renly","Durran"],
  "female": ["Shireen","Brienne","Cassana","Argella","Mya","Ravella","Alysanne","Donella","Marya","Elenei"] },
"crownlander": { "name": "Crownlander", "dyn": "of_place",
  "male": ["Gyles","Monford","Aurane","Ardrian","Jacelyn","Symon","Hallyne","Renfred","Rennifer","Duram","Bywater","Ossifer"],
  "female": ["Tanda","Lollys","Falyse","Ermesande","Senelle","Chataya","Marei","Jayde","Bellanora","Alerissa"] },
"dornish": { "name": "Dornish", "dyn": "of_place",
  "male": ["Doran","Oberyn","Quentyn","Trystane","Anders","Edric","Ryon","Daeron","Mors","Ulwyck","Cletus","Maron"],
  "female": ["Arianne","Ellaria","Nymeria","Tyene","Obara","Delonne","Larra","Loreza","Myria","Sylva"] },
"free_folk": { "name": "Free Folk", "dyn": "of_place",
  "male": ["Mance","Tormund","Craster","Orell","Styr","Jarl","Alfyn","Harma","Errok","Grigg","Bael","Sigorn"],
  "female": ["Ygritte","Val","Dalla","Osha","Gilly","Munda","Rowan","Ferny","Holly","Willow"] },
"valyrian": { "name": "Valyrian", "dyn": "plain",
  "family": ["Velaryon","Celtigar","Sunglass","Longwaters"],
  "male": ["Aegon","Aemon","Baelor","Daeron","Jacaerys","Lucerys","Maekar","Rhaegel","Valarr","Monterys"],
  "female": ["Rhaenys","Visenya","Daenerys","Rhaella","Shaera","Naerys","Elaena","Baela","Laena","Alysanne"] }
},

"settlementNames": {
  "default":     { "pre": ["Stone","Old","High","Deep","Cold","Long"], "suf": ["ford","mill","ton","field","bridge","hollow"] },
  "northmen":    { "pre": ["Winter","Wolf","Iron","Frost","Stone","White"], "suf": ["fell","hold","wood","ton","dale","harrow"] },
  "ironborn":    { "pre": ["Salt","Grey","Iron","Storm","Wyk","Drift"], "suf": ["port","cliff","keel","haven","rock","strand"] },
  "rivermen":    { "pre": ["River","Willow","Sally","Stone","Fair","Mud"], "suf": ["ford","mill","dance","market","bend","pool"] },
  "valemen":     { "pre": ["Snake","Iron","Long","Gull","Stone","Moon"], "suf": ["wood","oaks","bow","ton","town","vale"] },
  "westermen":   { "pre": ["Gold","Silver","Lann","Oxen","Corn","Feast"], "suf": ["mine","hill","port","ford","field","fires"] },
  "reachmen":    { "pre": ["Apple","Cider","Honey","Grape","Rose","White"], "suf": ["ton","hall","holt","shed","garden","grove"] },
  "stormlander": { "pre": ["Storm","Rain","Bronze","Black","Grand","Wind"], "suf": ["hall","wood","gate","haven","view","march"] },
  "crownlander": { "pre": ["King","Dusk","Rush","Sow","Flea","Iron"], "suf": ["wood","market","bottom","gate","well","port"] },
  "dornish":     { "pre": ["Sand","Sun","Lemon","Salt","Bone","Shadow"], "suf": ["stone","spear","wood","shore","city","well"] },
  "free_folk":   { "pre": ["White","Ruddy","Crag","Milk","Frost","Whale"], "suf": ["tree","hall","wick","water","bones","shore"] },
  "valyrian":    { "pre": ["Drift","Spice","Dragon","Salt","Tide","Claw"], "suf": ["mark","town","port","stone","water","keep"] }
},

"traits": {
  "wolf_bond": { "name": "Wolf-Bonded", "icon": "🐺", "desc": "A direwolf walks in their shadow.", "mar": 1, "opinion": 4, "noRandom": true },
  "warg": { "name": "Warg", "icon": "👁", "desc": "Slips behind the eyes of beasts.", "int": 2, "lea": 1, "opinion": -4, "noRandom": true, "inherit": 0.1 }
},

"buildings": {
  "temple":  { "name": { "default": "Great Sept", "pagan": "Godswood", "jewish": "Red Temple" }, "icon": "🛐", "cost": 70, "piety": 2, "pop": 5,
    "desc": "Stone raised toward the heavens — and remembered on earth." },
  "library": { "name": "Maester’s Tower", "icon": "📚", "cost": 80, "devMin": 4, "research": 1,
    "desc": "A rookery, a chained maester, and shelves of moldering wisdom. (+1 scholarship per season)" }
},

"tech": {
  "heavy_plough":  { "name": "Heavy Plough", "icon": "🌾", "cost": 30, "yearMin": 300,
    "desc": "Iron shares turn the deep clays. (+10% tax)", "fx": { "tax": 0.10 } },
  "three_field":   { "name": "Three-Field Rotation", "icon": "🌱", "cost": 60, "yearMin": 315, "req": "heavy_plough",
    "desc": "Two crops in the ground, one field at rest. (+10% tax, higher development ceiling)", "fx": { "tax": 0.10, "devCap": 1 } },
  "horse_collar":  { "name": "Horse Collar", "icon": "🐴", "cost": 100, "yearMin": 335, "req": "three_field",
    "desc": "A horse ploughs twice as fast as an ox. (+15% tax, higher development ceiling)", "fx": { "tax": 0.15, "devCap": 1 } },
  "ringworks":     { "name": "Ringforts", "icon": "🛡", "cost": 30, "yearMin": 300,
    "desc": "Earth and timber around every winter town. (+10% levy)", "fx": { "levy": 0.10 } },
  "stirrups":      { "name": "Knightly Cavalry", "icon": "🐎", "cost": 60, "yearMin": 315, "req": "ringworks",
    "desc": "Lances couched, banners streaming. (+5% battle odds)", "fx": { "battle": 0.05 } },
  "mail_hauberks": { "name": "Mail Hauberks", "icon": "⛓", "cost": 100, "yearMin": 335, "req": "stirrups",
    "desc": "A shirt of rings for every serious man. (+15% levy, +3% battle odds)", "fx": { "levy": 0.15, "battle": 0.03 } },
  "scriptoria":    { "name": "Ravenry", "icon": "🐦", "cost": 30, "yearMin": 300,
    "desc": "Dark wings, dark words — and knowledge that keeps. (+1 scholarship per season)", "fx": { "research": 1 } },
  "physicians":    { "name": "Maesters of the Citadel", "icon": "⚗", "cost": 60, "yearMin": 315, "req": "scriptoria",
    "desc": "A chained maester against fevers and wounds. (you live longer)", "fx": { "health": 0.012 } },
  "guild_charters":{ "name": "Guild Charters", "icon": "📯", "cost": 100, "yearMin": 335, "req": "physicians",
    "desc": "Chartered crafts and honest weights. (+10% tax, buildings cost 20% less)", "fx": { "tax": 0.10, "build": 0.20 } }
},

"items": {
  "damascene_blade": { "name": "Dragonbone Dagger", "icon": "🗡", "rarity": "fine", "value": 60, "fx": { "mar": 2, "battle": 0.03 },
    "desc": "Black bone and old steel. It does not forgive." },
  "hero_sword":      { "name": "Valyrian Steel Blade", "icon": "⚔", "rarity": "famed", "value": 250, "fx": { "mar": 3, "battle": 0.05, "prestige": 1 },
    "desc": "Spell-forged in the Freehold before the Doom. Songs already follow this sword — now they follow you." },
  "crown_of_old":    { "name": "Crown of the Old Kings", "icon": "👑", "rarity": "famed", "value": 220, "fx": { "prestige": 2, "dip": 1 },
    "desc": "A circlet of bronze and iron out of the age of heroes — and everybody bows to it." },
  "obsidian_knife":  { "name": "Dragonglass Knife", "icon": "🔪", "rarity": "fine", "value": 45, "fx": { "int": 1, "battle": 0.02 },
    "desc": "Frozen fire. The children of the forest knew its worth, and the crows still do." },
  "dragon_egg":      { "name": "Petrified Dragon Egg", "icon": "🥚", "rarity": "famed", "value": 280, "fx": { "prestige": 2 },
    "desc": "Stone, the maesters say. It is warm to the touch." },
  "myrish_eye":      { "name": "Myrish Eye", "icon": "🔭", "rarity": "fine", "value": 55, "fx": { "lea": 2 },
    "desc": "Far things brought near by Myrish lenses." },
  "weirwood_bow":    { "name": "Weirwood Bow", "icon": "🏹", "rarity": "fine", "value": 50, "fx": { "mar": 1, "battle": 0.02 },
    "desc": "Cut from a heart tree — some say the old gods watch along the arrow." }
},

"realms": [
{ "id": "west_francia", "name": "House Baratheon of King’s Landing", "color": "#e3c33f", "capital": "wessex", "aggression": 1 },
{ "id": "east_francia", "name": "House Lannister", "color": "#b8302e", "capital": "atil", "aggression": 2 },
{ "id": "lotharingia", "name": "House Tully", "color": "#3e6db0", "capital": "trondelag", "aggression": 0 },
{ "id": "italy", "name": "House Tyrell", "color": "#4e9a3e", "capital": "lorraine", "aggression": 1 },
{ "id": "papacy", "name": "House Hightower", "color": "#d8d4c4", "capital": "gwynedd", "aggression": 0 },
{ "id": "benevento", "name": "House Redwyne", "color": "#7d2740", "capital": "dublin", "aggression": 0 },
{ "id": "emirate_bari", "name": "House Florent", "color": "#9a7a2f", "capital": "burgundy", "aggression": 1 },
{ "id": "venice", "name": "House Tarly", "color": "#3d6b35", "capital": "champagne", "aggression": 1 },
{ "id": "byzantium", "name": "House Stark", "color": "#aeb6c2", "capital": "baghdad", "aggression": 1 },
{ "id": "cordoba", "name": "House Martell", "color": "#d0722f", "capital": "galicia", "aggression": 1 },
{ "id": "asturias", "name": "House Yronwood", "color": "#a89a5f", "capital": "lisboa", "aggression": 1 },
{ "id": "navarre", "name": "House Dayne", "color": "#7a6fb8", "capital": "aquitaine", "aggression": 0 },
{ "id": "brittany", "name": "House Arryn", "color": "#9cc3e4", "capital": "croatia", "aggression": 0 },
{ "id": "wessex", "name": "House Baratheon of Storm’s End", "color": "#4f9a55", "capital": "livonia", "aggression": 1 },
{ "id": "mercia", "name": "House Baratheon of Dragonstone", "color": "#8a7a2e", "capital": "constantinople", "aggression": 1 },
{ "id": "east_anglia", "name": "House Swann", "color": "#9a9aa4", "capital": "uppland", "aggression": 0 },
{ "id": "york", "name": "House Dondarrion", "color": "#5a4a8a", "capital": "mercia", "aggression": 0 },
{ "id": "alba", "name": "House Tarth", "color": "#6f8fc8", "capital": "crete", "aggression": 0 },
{ "id": "gwynedd", "name": "House Estermont", "color": "#4a7a5a", "capital": "gotland", "aggression": 0 },
{ "id": "dublin", "name": "House Grafton", "color": "#c08a30", "capital": "serbia", "aggression": 0 },
{ "id": "munster", "name": "House Royce", "color": "#8f7a45", "capital": "belgrade", "aggression": 1 },
{ "id": "connacht", "name": "House Baelish", "color": "#3f8a7a", "capital": "provence", "aggression": 0 },
{ "id": "ulster", "name": "The Stoneborn of Skagos", "color": "#606a5a", "capital": "cyprus", "aggression": 1 },
{ "id": "denmark", "name": "House Greyjoy", "color": "#4a4f58", "capital": "jutland", "aggression": 2 },
{ "id": "norway", "name": "House Frey", "color": "#5a6a8a", "capital": "gotaland", "aggression": 1 },
{ "id": "sweden", "name": "House Blackwood", "color": "#463a52", "capital": "polotsk", "aggression": 1 },
{ "id": "rus", "name": "House Bracken", "color": "#a67a35", "capital": "kiev", "aggression": 1 },
{ "id": "poland", "name": "House Mallister", "color": "#7060a8", "capital": "vestfold", "aggression": 0 },
{ "id": "wends", "name": "House Darry", "color": "#5f452c", "capital": "prussia", "aggression": 0 },
{ "id": "prussia", "name": "House Mooton", "color": "#c05a4a", "capital": "lithuania", "aggression": 0 },
{ "id": "lithuania", "name": "House Whent", "color": "#b0a640", "capital": "pomerania", "aggression": 0 },
{ "id": "finland", "name": "House Bolton", "color": "#d78ea2", "capital": "medina", "aggression": 1 },
{ "id": "bohemia", "name": "House Karstark", "color": "#3c4348", "capital": "antioch", "aggression": 0 },
{ "id": "moravia", "name": "House Umber", "color": "#7a4a2f", "capital": "aswan", "aggression": 1 },
{ "id": "croatia", "name": "House Manderly", "color": "#3f8f8f", "capital": "tuscany", "aggression": 0 },
{ "id": "serbia", "name": "House Mormont", "color": "#356a44", "capital": "tangier", "aggression": 0 },
{ "id": "bulgaria", "name": "House Glover", "color": "#93402c", "capital": "sevilla", "aggression": 0 },
{ "id": "magyars", "name": "House Reed", "color": "#4a6f3a", "capital": "aleppo", "aggression": 0 },
{ "id": "khazaria", "name": "House Dustin", "color": "#71513c", "capital": "mosul", "aggression": 0 },
{ "id": "armenia", "name": "House Ryswell", "color": "#8a6a34", "capital": "basra", "aggression": 0 },
{ "id": "georgia", "name": "House Hornwood", "color": "#a05a20", "capital": "fars", "aggression": 0 },
{ "id": "abbasid", "name": "The Night’s Watch", "color": "#26262e", "capital": "tahert", "aggression": 0 },
{ "id": "emirate_crete", "name": "The Free Folk", "color": "#8a7a6a", "capital": "north_w", "aggression": 2 },
{ "id": "aghlabids", "name": "The Thenns", "color": "#8c5a2a", "capital": "lapland", "aggression": 1 },
{ "id": "idrisids", "name": "Hardhome", "color": "#5a6a72", "capital": "sijilmasa", "aggression": 1 },
{ "id": "rustamids", "name": "The Frozen Shore", "color": "#a8c4d0", "capital": "kara_kum", "aggression": 1 },
{ "id": "sijilmasa", "name": "House Crakehall", "color": "#7d5a42", "capital": "kibyrrhaiot", "aggression": 0 },
{ "id": "yemen", "name": "House Marbrand", "color": "#c07a30", "capital": "dyrrachion", "aggression": 0 },
{ "id": "makuria", "name": "House Farman", "color": "#6a9ab0", "capital": "sicily", "aggression": 0 }
],

"straits": [
["lisboa","mercia"], ["badajoz","cornwall"], ["croatia","prussia"],
["cyprus","tlemcen"], ["constantinople","cherson"], ["corsica","serbia"],
["crete","gotland"], ["zealand","thessalonica"], ["sicily","alania"]
],

"scripted": [
{ "year": 298, "type": "conquest", "realm": "west_francia", "targets": [],
  "news": "King Robert Baratheon is dead — gored by a boar in the kingswood. Joffrey of Houses Baratheon and Lannister is crowned, and ravens whisper of treason at court." },
{ "year": 299, "type": "conquest", "realm": "east_francia", "targets": ["krakow","kiev"],
  "news": "The War of the Five Kings! Lannister hosts pour through the Golden Tooth and set the riverlands ablaze." },
{ "year": 300, "type": "conquest", "realm": "denmark", "targets": ["jibal","granada"],
  "news": "The krakens rise! Ironborn longships fall upon the western shores of the North." },
{ "year": 302, "type": "conquest", "realm": "emirate_crete",
  "newRealm": { "id": "the_others", "name": "The Others", "color": "#c9ecf6", "capital": "sijilmasa", "aggression": 2 },
  "targets": ["sijilmasa","ural_w","rus_n","volga_b"],
  "news": "Cold winds rise. The dead walk in the haunted forest and Hardhome falls silent. The Long Night gathers beyond the Wall." },
{ "year": 869, "type": "conquest", "realm": "abbasid", "targets": [],
  "news": "The maesters mark a rare conjunction of the wandering stars." },
{ "year": 878, "type": "conquest", "realm": "abbasid", "targets": [],
  "news": "The Citadel proclaims a great anniversary of Aegon’s Conquest." },
{ "year": 895, "type": "conquest", "realm": "abbasid", "targets": [],
  "news": "Singers tell again the tale of the Long Night, thousands of years gone." }
],

"provinces": [
{ "id": "galicia", "name": "Sunspear", "x": 9.0, "y": 10.4, "realm": "cordoba", "culture": "dornish", "religion": "the_seven", "terrain": "desert", "dev": 6 },
{ "id": "asturias", "name": "Godsgrace", "x": 5.6, "y": 9.8, "realm": "cordoba", "culture": "dornish", "religion": "the_seven", "terrain": "farmland", "dev": 4 },
{ "id": "castile", "name": "Lemonwood", "x": 6.6, "y": 8.6, "realm": "cordoba", "culture": "dornish", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "navarre", "name": "The Tor", "x": 5.9, "y": 12.1, "realm": "cordoba", "culture": "dornish", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "barcelona", "name": "Ghost Hill", "x": 7.9, "y": 11.7, "realm": "cordoba", "culture": "dornish", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "zaragoza", "name": "Vaith", "x": 2.6, "y": 9.9, "realm": "cordoba", "culture": "dornish", "religion": "the_seven", "terrain": "desert", "dev": 2 },
{ "id": "toledo", "name": "Hellholt", "x": 0.6, "y": 11.1, "realm": "cordoba", "culture": "dornish", "religion": "the_seven", "terrain": "desert", "dev": 3 },
{ "id": "valencia", "name": "Salt Shore", "x": -2.4, "y": 8.3, "realm": "cordoba", "culture": "dornish", "religion": "the_seven", "terrain": "desert", "dev": 2 },
{ "id": "cordoba", "name": "Sandstone", "x": -1.0, "y": 9.8, "realm": "cordoba", "culture": "dornish", "religion": "the_seven", "terrain": "desert", "dev": 2 },
{ "id": "lisboa", "name": "Yronwood", "x": 1.9, "y": 12.7, "realm": "asturias", "culture": "dornish", "religion": "the_seven", "terrain": "hills", "dev": 4 },
{ "id": "badajoz", "name": "Skyreach", "x": -1.1, "y": 12.5, "realm": "asturias", "culture": "dornish", "religion": "the_seven", "terrain": "mountains", "dev": 2 },
{ "id": "paris", "name": "Kingsgrave", "x": -2.4, "y": 11.7, "realm": "asturias", "culture": "dornish", "religion": "the_seven", "terrain": "mountains", "dev": 2 },
{ "id": "brittany", "name": "Blackmont", "x": -3.3, "y": 10.9, "realm": "navarre", "culture": "dornish", "religion": "the_seven", "terrain": "mountains", "dev": 2 },
{ "id": "anjou", "name": "High Hermitage", "x": -3.7, "y": 9.9, "realm": "navarre", "culture": "dornish", "religion": "the_seven", "terrain": "hills", "dev": 2 },
{ "id": "aquitaine", "name": "Starfall", "x": -4.4, "y": 9.1, "realm": "navarre", "culture": "dornish", "religion": "the_seven", "terrain": "hills", "dev": 4 },
{ "id": "gwynedd", "name": "Oldtown", "x": -8.4, "y": 11.0, "realm": "papacy", "culture": "reachmen", "religion": "the_seven", "terrain": "farmland", "dev": 9 },
{ "id": "dublin", "name": "The Arbor", "x": -10.6, "y": 9.7, "realm": "benevento", "culture": "reachmen", "religion": "the_seven", "terrain": "farmland", "dev": 5 },
{ "id": "toulouse", "name": "Three Towers", "x": -9.1, "y": 12.7, "realm": "papacy", "culture": "reachmen", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "lyon", "name": "Honeyholt", "x": -7.7, "y": 12.3, "realm": "papacy", "culture": "reachmen", "religion": "the_seven", "terrain": "farmland", "dev": 4 },
{ "id": "burgundy", "name": "Brightwater Keep", "x": -6.5, "y": 13.7, "realm": "emirate_bari", "culture": "reachmen", "religion": "the_seven", "terrain": "farmland", "dev": 4 },
{ "id": "champagne", "name": "Horn Hill", "x": -5.1, "y": 12.9, "realm": "venice", "culture": "reachmen", "religion": "the_seven", "terrain": "hills", "dev": 4 },
{ "id": "lorraine", "name": "Highgarden", "x": -4.6, "y": 16.7, "realm": "italy", "culture": "reachmen", "religion": "the_seven", "terrain": "farmland", "dev": 7 },
{ "id": "frisia", "name": "The Shields", "x": -8.3, "y": 20.5, "realm": "italy", "culture": "reachmen", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "franconia", "name": "Old Oak", "x": -8.2, "y": 24.7, "realm": "italy", "culture": "reachmen", "religion": "the_seven", "terrain": "forest", "dev": 3 },
{ "id": "saxony", "name": "Red Lake", "x": -6.3, "y": 22.9, "realm": "italy", "culture": "reachmen", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "swabia", "name": "Goldengrove", "x": -4.3, "y": 22.5, "realm": "italy", "culture": "reachmen", "religion": "the_seven", "terrain": "farmland", "dev": 4 },
{ "id": "bavaria", "name": "Cider Hall", "x": -1.5, "y": 17.5, "realm": "italy", "culture": "reachmen", "religion": "the_seven", "terrain": "farmland", "dev": 4 },
{ "id": "ostmark", "name": "Ashford", "x": 0.5, "y": 16.3, "realm": "italy", "culture": "reachmen", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "thuringia", "name": "Bitterbridge", "x": -0.5, "y": 20.3, "realm": "italy", "culture": "reachmen", "religion": "the_seven", "terrain": "farmland", "dev": 4 },
{ "id": "lombardy", "name": "Longtable", "x": -1.3, "y": 18.9, "realm": "italy", "culture": "reachmen", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "venice", "name": "Tumbleton", "x": 0.7, "y": 22.1, "realm": "italy", "culture": "reachmen", "religion": "the_seven", "terrain": "farmland", "dev": 4 },
{ "id": "roma", "name": "Grassy Vale", "x": 1.1, "y": 18.7, "realm": "italy", "culture": "reachmen", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "benevento", "name": "Bronzegate", "x": 3.9, "y": 20.7, "realm": "wessex", "culture": "stormlander", "religion": "the_seven", "terrain": "forest", "dev": 3 },
{ "id": "bari", "name": "Felwood", "x": 2.9, "y": 19.5, "realm": "wessex", "culture": "stormlander", "religion": "the_seven", "terrain": "forest", "dev": 3 },
{ "id": "cornwall", "name": "Summerhall", "x": 0.9, "y": 14.9, "realm": "wessex", "culture": "stormlander", "religion": "the_seven", "terrain": "hills", "dev": 2 },
{ "id": "mercia", "name": "Blackhaven", "x": 2.3, "y": 13.7, "realm": "york", "culture": "stormlander", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "east_anglia", "name": "Mistwood", "x": 6.2, "y": 14.9, "realm": "wessex", "culture": "stormlander", "religion": "the_seven", "terrain": "forest", "dev": 2 },
{ "id": "alba", "name": "The Rain House", "x": 7.0, "y": 14.4, "realm": "wessex", "culture": "stormlander", "religion": "the_seven", "terrain": "forest", "dev": 2 },
{ "id": "munster", "name": "Haystack Hall", "x": 4.5, "y": 21.5, "realm": "wessex", "culture": "stormlander", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "livonia", "name": "Storm’s End", "x": 5.3, "y": 19.3, "realm": "wessex", "culture": "stormlander", "religion": "the_seven", "terrain": "hills", "dev": 5 },
{ "id": "uppland", "name": "Stonehelm", "x": 4.7, "y": 14.5, "realm": "east_anglia", "culture": "stormlander", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "gotland", "name": "Greenstone", "x": 6.9, "y": 16.0, "realm": "gwynedd", "culture": "stormlander", "religion": "the_seven", "terrain": "hills", "dev": 2 },
{ "id": "crete", "name": "Tarth", "x": 7.45, "y": 18.6, "realm": "alba", "culture": "stormlander", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "hellas", "name": "Griffin’s Roost", "x": 6.1, "y": 16.9, "realm": "wessex", "culture": "stormlander", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "wessex", "name": "King’s Landing", "x": 2.95, "y": 23.8, "realm": "west_francia", "culture": "crownlander", "religion": "the_seven", "terrain": "farmland", "dev": 10 },
{ "id": "normandy", "name": "The Kingswood", "x": 3.5, "y": 22.3, "realm": "west_francia", "culture": "crownlander", "religion": "the_seven", "terrain": "forest", "dev": 3 },
{ "id": "kent", "name": "Duskendale", "x": 3.95, "y": 25.3, "realm": "west_francia", "culture": "crownlander", "religion": "the_seven", "terrain": "farmland", "dev": 5 },
{ "id": "flanders", "name": "Rosby", "x": 3.4, "y": 24.5, "realm": "west_francia", "culture": "crownlander", "religion": "the_seven", "terrain": "farmland", "dev": 4 },
{ "id": "connacht", "name": "The Antlers", "x": 1.3, "y": 25.3, "realm": "west_francia", "culture": "crownlander", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "ulster", "name": "Stokeworth", "x": 2.6, "y": 25.0, "realm": "west_francia", "culture": "crownlander", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "cherson", "name": "Crackclaw Point", "x": 5.8, "y": 25.7, "realm": "west_francia", "culture": "crownlander", "religion": "the_seven", "terrain": "forest", "dev": 2 },
{ "id": "armeniakon", "name": "Rook’s Rest", "x": 4.8, "y": 25.1, "realm": "west_francia", "culture": "crownlander", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "constantinople", "name": "Dragonstone", "x": 6.65, "y": 23.2, "realm": "mercia", "culture": "valyrian", "religion": "the_seven", "terrain": "hills", "dev": 5 },
{ "id": "opsikion", "name": "Massey’s Hook", "x": 6.2, "y": 21.4, "realm": "mercia", "culture": "crownlander", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "trondelag", "name": "Riverrun", "x": -4.4, "y": 30.7, "realm": "lotharingia", "culture": "rivermen", "religion": "the_seven", "terrain": "farmland", "dev": 5 },
{ "id": "vestfold", "name": "Seagard", "x": -4.2, "y": 35.1, "realm": "poland", "culture": "rivermen", "religion": "the_seven", "terrain": "farmland", "dev": 4 },
{ "id": "gotaland", "name": "The Twins", "x": -1.9, "y": 33.5, "realm": "norway", "culture": "rivermen", "religion": "the_seven", "terrain": "farmland", "dev": 4 },
{ "id": "novgorod", "name": "Fairmarket", "x": -1.5, "y": 31.3, "realm": "lotharingia", "culture": "rivermen", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "polotsk", "name": "Raventree Hall", "x": -3.5, "y": 28.9, "realm": "sweden", "culture": "rivermen", "religion": "old_gods", "terrain": "forest", "dev": 3 },
{ "id": "kiev", "name": "Stone Hedge", "x": -1.9, "y": 28.3, "realm": "rus", "culture": "rivermen", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "poland", "name": "Acorn Hall", "x": -0.7, "y": 26.7, "realm": "lotharingia", "culture": "rivermen", "religion": "the_seven", "terrain": "forest", "dev": 3 },
{ "id": "krakow", "name": "Pinkmaiden", "x": -3.1, "y": 26.9, "realm": "lotharingia", "culture": "rivermen", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "pomerania", "name": "Harrenhal", "x": 1.5, "y": 27.0, "realm": "lithuania", "culture": "rivermen", "religion": "the_seven", "terrain": "farmland", "dev": 4 },
{ "id": "prussia", "name": "Darry", "x": 2.2, "y": 28.5, "realm": "wends", "culture": "rivermen", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "lithuania", "name": "Maidenpool", "x": 3.1, "y": 26.6, "realm": "prussia", "culture": "rivermen", "religion": "the_seven", "terrain": "farmland", "dev": 4 },
{ "id": "finland", "name": "Saltpans", "x": 4.2, "y": 27.1, "realm": "prussia", "culture": "rivermen", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "bohemia", "name": "Wayfarer’s Rest", "x": -4.8, "y": 28.7, "realm": "lotharingia", "culture": "rivermen", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "moravia", "name": "Atranta", "x": -4.4, "y": 26.4, "realm": "lotharingia", "culture": "rivermen", "religion": "the_seven", "terrain": "forest", "dev": 2 },
{ "id": "pannonia", "name": "The Mummer’s Ford", "x": -1.6, "y": 25.9, "realm": "lotharingia", "culture": "rivermen", "religion": "the_seven", "terrain": "farmland", "dev": 2 },
{ "id": "croatia", "name": "The Eyrie", "x": 2.9, "y": 29.9, "realm": "brittany", "culture": "valemen", "religion": "the_seven", "terrain": "mountains", "dev": 5 },
{ "id": "serbia", "name": "Gulltown", "x": 6.4, "y": 27.8, "realm": "dublin", "culture": "valemen", "religion": "the_seven", "terrain": "farmland", "dev": 6 },
{ "id": "belgrade", "name": "Runestone", "x": 6.3, "y": 29.0, "realm": "munster", "culture": "valemen", "religion": "the_seven", "terrain": "hills", "dev": 4 },
{ "id": "pliska", "name": "The Redfort", "x": 4.5, "y": 27.9, "realm": "brittany", "culture": "valemen", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "sredets", "name": "Wickenden", "x": 5.3, "y": 26.9, "realm": "brittany", "culture": "valemen", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "wallachia", "name": "Heart’s Home", "x": 5.7, "y": 30.4, "realm": "brittany", "culture": "valemen", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "etelkoz", "name": "Strongsong", "x": 3.7, "y": 31.1, "realm": "brittany", "culture": "valemen", "religion": "the_seven", "terrain": "mountains", "dev": 3 },
{ "id": "sarkel", "name": "Coldwater Burn", "x": 6.1, "y": 31.5, "realm": "brittany", "culture": "valemen", "religion": "the_seven", "terrain": "hills", "dev": 2 },
{ "id": "provence", "name": "The Fingers", "x": 7.9, "y": 29.5, "realm": "connacht", "culture": "valemen", "religion": "the_seven", "terrain": "hills", "dev": 2 },
{ "id": "corsica", "name": "Sisterton", "x": 5.2, "y": 32.4, "realm": "brittany", "culture": "valemen", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "atil", "name": "Casterly Rock", "x": -8.1, "y": 28.9, "realm": "east_francia", "culture": "westermen", "religion": "the_seven", "terrain": "hills", "dev": 8 },
{ "id": "kairouan", "name": "Lannisport", "x": -8.1, "y": 27.9, "realm": "east_francia", "culture": "westermen", "religion": "the_seven", "terrain": "farmland", "dev": 7 },
{ "id": "alania", "name": "Kayce", "x": -7.6, "y": 30.2, "realm": "east_francia", "culture": "westermen", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "calabria", "name": "The Crag", "x": -6.8, "y": 31.4, "realm": "east_francia", "culture": "westermen", "religion": "the_seven", "terrain": "hills", "dev": 2 },
{ "id": "thessalonica", "name": "The Banefort", "x": -5.8, "y": 32.7, "realm": "east_francia", "culture": "westermen", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "armenia", "name": "Castamere", "x": -6.3, "y": 30.6, "realm": "east_francia", "culture": "westermen", "religion": "the_seven", "terrain": "hills", "dev": 2 },
{ "id": "dyrrachion", "name": "Ashemark", "x": -5.3, "y": 31.1, "realm": "yemen", "culture": "westermen", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "thrakesion", "name": "The Golden Tooth", "x": -4.9, "y": 29.7, "realm": "east_francia", "culture": "westermen", "religion": "the_seven", "terrain": "mountains", "dev": 3 },
{ "id": "anatolikon", "name": "Sarsfield", "x": -6.9, "y": 28.4, "realm": "east_francia", "culture": "westermen", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "cappadocia", "name": "Silverhill", "x": -5.5, "y": 27.5, "realm": "east_francia", "culture": "westermen", "religion": "the_seven", "terrain": "hills", "dev": 3 },
{ "id": "chaldia", "name": "Deep Den", "x": -4.5, "y": 26.3, "realm": "east_francia", "culture": "westermen", "religion": "the_seven", "terrain": "mountains", "dev": 2 },
{ "id": "kibyrrhaiot", "name": "Crakehall", "x": -7.3, "y": 25.9, "realm": "sijilmasa", "culture": "westermen", "religion": "the_seven", "terrain": "forest", "dev": 4 },
{ "id": "georgia", "name": "Cornfield", "x": -6.0, "y": 25.2, "realm": "sijilmasa", "culture": "westermen", "religion": "the_seven", "terrain": "farmland", "dev": 3 },
{ "id": "sicily", "name": "Fair Isle", "x": -9.6, "y": 30.6, "realm": "makuria", "culture": "westermen", "religion": "the_seven", "terrain": "hills", "dev": 4 },
{ "id": "jutland", "name": "Pyke", "x": -6.3, "y": 36.3, "realm": "denmark", "culture": "ironborn", "religion": "drowned_god", "terrain": "hills", "dev": 5 },
{ "id": "zealand", "name": "Great Wyk", "x": -9.2, "y": 36.9, "realm": "denmark", "culture": "ironborn", "religion": "drowned_god", "terrain": "hills", "dev": 3 },
{ "id": "skane", "name": "Old Wyk", "x": -7.5, "y": 35.9, "realm": "denmark", "culture": "ironborn", "religion": "drowned_god", "terrain": "hills", "dev": 2 },
{ "id": "veligrad", "name": "Saltcliffe", "x": -8.6, "y": 36.2, "realm": "denmark", "culture": "ironborn", "religion": "drowned_god", "terrain": "hills", "dev": 2 },
{ "id": "york", "name": "Harlaw", "x": -6.1, "y": 37.2, "realm": "denmark", "culture": "ironborn", "religion": "drowned_god", "terrain": "hills", "dev": 3 },
{ "id": "aleppo", "name": "Greywater Watch", "x": -2.3, "y": 35.5, "realm": "magyars", "culture": "northmen", "religion": "old_gods", "terrain": "marsh", "dev": 1 },
{ "id": "damascus", "name": "Moat Cailin", "x": -0.8, "y": 36.3, "realm": "byzantium", "culture": "northmen", "religion": "old_gods", "terrain": "marsh", "dev": 1 },
{ "id": "jerusalem", "name": "Flint’s Finger", "x": -4.8, "y": 39.1, "realm": "byzantium", "culture": "northmen", "religion": "old_gods", "terrain": "hills", "dev": 1 },
{ "id": "mosul", "name": "Barrowton", "x": -2.1, "y": 39.5, "realm": "khazaria", "culture": "northmen", "religion": "old_gods", "terrain": "farmland", "dev": 3 },
{ "id": "baghdad", "name": "Winterfell", "x": 0.1, "y": 43.3, "realm": "byzantium", "culture": "northmen", "religion": "old_gods", "terrain": "farmland", "dev": 6 },
{ "id": "basra", "name": "The Rills", "x": -3.9, "y": 40.9, "realm": "armenia", "culture": "northmen", "religion": "old_gods", "terrain": "farmland", "dev": 2 },
{ "id": "azerbaijan", "name": "Torrhen’s Square", "x": -1.7, "y": 41.7, "realm": "byzantium", "culture": "northmen", "religion": "old_gods", "terrain": "farmland", "dev": 3 },
{ "id": "jibal", "name": "The Stony Shore", "x": -5.8, "y": 42.5, "realm": "byzantium", "culture": "northmen", "religion": "old_gods", "terrain": "hills", "dev": 1 },
{ "id": "sevilla", "name": "Deepwood Motte", "x": -5.6, "y": 45.9, "realm": "bulgaria", "culture": "northmen", "religion": "old_gods", "terrain": "forest", "dev": 2 },
{ "id": "granada", "name": "Sea Dragon Point", "x": -6.9, "y": 44.3, "realm": "bulgaria", "culture": "northmen", "religion": "old_gods", "terrain": "forest", "dev": 1 },
{ "id": "tangier", "name": "Bear Island", "x": -8.0, "y": 46.6, "realm": "serbia", "culture": "northmen", "religion": "old_gods", "terrain": "forest", "dev": 2 },
{ "id": "fars", "name": "Hornwood", "x": 2.7, "y": 41.1, "realm": "georgia", "culture": "northmen", "religion": "old_gods", "terrain": "forest", "dev": 2 },
{ "id": "medina", "name": "The Dreadfort", "x": 3.5, "y": 43.1, "realm": "finland", "culture": "northmen", "religion": "old_gods", "terrain": "hills", "dev": 3 },
{ "id": "antioch", "name": "Karhold", "x": 6.5, "y": 44.1, "realm": "bohemia", "culture": "northmen", "religion": "old_gods", "terrain": "forest", "dev": 3 },
{ "id": "tuscany", "name": "White Harbor", "x": 3.8, "y": 34.7, "realm": "croatia", "culture": "northmen", "religion": "the_seven", "terrain": "farmland", "dev": 6 },
{ "id": "mecca", "name": "Ramsgate", "x": 5.5, "y": 35.1, "realm": "croatia", "culture": "northmen", "religion": "the_seven", "terrain": "farmland", "dev": 2 },
{ "id": "yemen", "name": "Oldcastle", "x": 4.7, "y": 36.7, "realm": "croatia", "culture": "northmen", "religion": "the_seven", "terrain": "farmland", "dev": 2 },
{ "id": "cairo", "name": "The Sheepshead Hills", "x": 4.3, "y": 39.4, "realm": "croatia", "culture": "northmen", "religion": "the_seven", "terrain": "hills", "dev": 2 },
{ "id": "sardinia", "name": "Widow’s Watch", "x": 6.7, "y": 35.3, "realm": "croatia", "culture": "northmen", "religion": "old_gods", "terrain": "forest", "dev": 2 },
{ "id": "alexandria", "name": "The Grey Cliffs", "x": 5.4, "y": 38.2, "realm": "byzantium", "culture": "northmen", "religion": "old_gods", "terrain": "forest", "dev": 2 },
{ "id": "aswan", "name": "Last Hearth", "x": 2.5, "y": 47.7, "realm": "moravia", "culture": "northmen", "religion": "old_gods", "terrain": "forest", "dev": 2 },
{ "id": "dongola", "name": "The Lonely Hills", "x": 4.1, "y": 46.1, "realm": "moravia", "culture": "northmen", "religion": "old_gods", "terrain": "hills", "dev": 1 },
{ "id": "barqa", "name": "Long Lake", "x": 0.5, "y": 45.5, "realm": "byzantium", "culture": "northmen", "religion": "old_gods", "terrain": "forest", "dev": 1 },
{ "id": "cyprus", "name": "Skagos", "x": 6.9, "y": 47.6, "realm": "ulster", "culture": "northmen", "religion": "old_gods", "terrain": "hills", "dev": 1 },
{ "id": "tripoli", "name": "Queenscrown", "x": 1.9, "y": 48.1, "realm": "abbasid", "culture": "northmen", "religion": "old_gods", "terrain": "farmland", "dev": 1 },
{ "id": "tahert", "name": "Castle Black", "x": 0.5, "y": 49.5, "realm": "abbasid", "culture": "northmen", "religion": "old_gods", "terrain": "hills", "dev": 2 },
{ "id": "tlemcen", "name": "Eastwatch-by-the-Sea", "x": 4.5, "y": 49.0, "realm": "abbasid", "culture": "northmen", "religion": "old_gods", "terrain": "tundra", "dev": 1 },
{ "id": "fes", "name": "The Shadow Tower", "x": -4.5, "y": 49.3, "realm": "abbasid", "culture": "northmen", "religion": "old_gods", "terrain": "tundra", "dev": 1 },
{ "id": "sijilmasa", "name": "Hardhome", "x": 5.7, "y": 52.5, "realm": "idrisids", "culture": "free_folk", "religion": "old_gods", "terrain": "tundra", "dev": 1 },
{ "id": "north_w", "name": "The Haunted Forest", "x": 0.7, "y": 52.1, "realm": "emirate_crete", "culture": "free_folk", "religion": "old_gods", "terrain": "forest", "dev": 1 },
{ "id": "ural_w", "name": "Craster’s Keep", "x": 2.7, "y": 51.1, "realm": "emirate_crete", "culture": "free_folk", "religion": "old_gods", "terrain": "forest", "dev": 1 },
{ "id": "volga_b", "name": "Whitetree", "x": 0.3, "y": 50.7, "realm": "emirate_crete", "culture": "free_folk", "religion": "old_gods", "terrain": "forest", "dev": 1 },
{ "id": "rus_n", "name": "The Milkwater", "x": -2.5, "y": 51.7, "realm": "emirate_crete", "culture": "free_folk", "religion": "old_gods", "terrain": "tundra", "dev": 1 },
{ "id": "lapland", "name": "Thenn", "x": -1.5, "y": 54.1, "realm": "aghlabids", "culture": "free_folk", "religion": "old_gods", "terrain": "hills", "dev": 2 },
{ "id": "kara_kum", "name": "The Frozen Shore", "x": -6.7, "y": 53.1, "realm": "rustamids", "culture": "free_folk", "religion": "old_gods", "terrain": "tundra", "dev": 1 },
{ "id": "sahara_w", "name": "The Frostfangs", "x": -4.3, "y": 53.6, "wasteland": true, "terrain": "mountains" },
{ "id": "sahara_c", "name": "Land of Always Winter", "x": -1.0, "y": 55.7, "wasteland": true, "terrain": "tundra" },
{ "id": "sahara_e", "name": "The White Waste", "x": 3.4, "y": 55.5, "wasteland": true, "terrain": "tundra" },
{ "id": "sahel", "name": "The Red Mountains", "x": 0.1, "y": 13.1, "wasteland": true, "terrain": "mountains" },
{ "id": "nubia_d", "name": "The Deep Sands", "x": 3.7, "y": 10.3, "wasteland": true, "terrain": "desert" },
{ "id": "arabia_d", "name": "Mountains of the Moon", "x": 1.1, "y": 30.3, "wasteland": true, "terrain": "mountains" },
{ "id": "nefud", "name": "The Torrentine Heights", "x": -3.0, "y": 12.6, "wasteland": true, "terrain": "mountains" },
{ "id": "syrian_d", "name": "The Wolfswood", "x": -3.1, "y": 45.1, "wasteland": true, "terrain": "forest" }
],

"events": [

{ "id": "got_direwolf", "title": "A Direwolf Pup",
  "text": "Hunters find a direwolf dead in a snowdrift — and one pup still breathing, no bigger than a cat. The old men mutter that no direwolf has been seen south of the Wall in two hundred years.",
  "trigger": { "cultures": ["northmen"], "minAge": 8, "chance": 0.3 },
  "once": true, "weight": 7,
  "options": [
    { "label": "Raise it as your own.", "effects": { "addTrait": "wolf_bond", "setFlag": "has_wolf", "log": "{name} took in a direwolf pup. It grew." } },
    { "label": "Sell it to a curious lordling.", "effects": { "gold": 12 } },
    { "label": "Leave it to the old gods.", "effects": { "piety": 3 } }
  ] },

{ "id": "got_wolf_dreams", "title": "Wolf Dreams",
  "text": "At night you run on four legs through black pines, and the snow tastes of iron. Each morning you wake with the smell of the kill in your nose.",
  "trigger": { "flags": ["has_wolf"], "chance": 0.5 },
  "once": true, "weight": 6,
  "options": [
    { "label": "Open the door in your mind.", "effects": { "addTrait": "warg", "piety": 4, "log": "{name} learned to wear a wolf’s skin." } },
    { "label": "Bar it shut. Such dreams are not for men.", "effects": { "skills": { "int": 1 } } }
  ] },

{ "id": "got_nw_recruiter", "title": "A Crow Comes Begging",
  "text": "A wandering crow of the Night’s Watch stands at the door in travel-stained black, asking men for the Wall. ‘The Watch has never had greater need,’ he says, and his eyes say he believes it.",
  "trigger": { "tierMax": 2, "chance": 0.3 },
  "weight": 5, "cooldown": 24,
  "options": [
    { "label": "Feed him and hear the news from the Wall.", "effects": { "gold": -2, "piety": 3 } },
    { "label": "Hand over the poacher rotting in the lord’s cell.", "effects": { "gold": 8, "popularOpinion": -4 } },
    { "label": "Say the words. Take the black.", "require": { "sex": "m", "married": false, "maxAge": 45 },
      "desc": "Night gathers, and now your watch begins. It shall not end until your death.",
      "effects": { "profession": "soldier", "setFlag": "black_brother", "prestige": 12,
        "log": "{name} took the black and was sworn to the Night’s Watch." } }
  ] },

{ "id": "got_wall_ranging", "title": "Ranging Beyond the Wall",
  "text": "The Lord Commander sends rangers north through the tunnel. The haunted forest is quiet — too quiet, the older crows say — and the wildling villages stand empty.",
  "trigger": { "flags": ["black_brother"], "chance": 0.5 },
  "weight": 6, "cooldown": 12,
  "options": [
    { "label": "Ride in the van.", "chance": "battle",
      "success": { "text": "You bring the ranging home alive, and word of your steadiness reaches the Lord Commander.", "effects": { "prestige": 10, "skills": { "mar": 1 } } },
      "failure": { "text": "Something followed you in the dark between the trees. Not all of you came back whole.", "effects": { "health": -2 } } },
    { "label": "Stand your watch atop the ice.", "effects": { "skills": { "ste": 1 } } },
    { "label": "Slip away south.", "desc": "Deserters lose their heads.", "chance": 0.5,
      "success": { "text": "You shed the black cloak in a stream and walk south a free man — nameless, and forsworn.", "effects": { "clearFlag": "black_brother", "prestige": -20, "profession": "farmer" } },
      "failure": { "text": "Riders in black run you down within a day. You buy your life with blood and are dragged back to the Wall.", "effects": { "health": -5, "prestige": -12 } } }
  ] },

{ "id": "got_wildling_raid", "title": "Raiders Over the Wall",
  "text": "Wildlings have slipped over the Wall — a raiding band moving through the district, taking axes, women, and every scrap of bread.",
  "trigger": { "cultures": ["northmen"], "chance": 0.22 },
  "weight": 5, "cooldown": 12,
  "options": [
    { "label": "Stand with your neighbors and fight.", "chance": "battle",
      "success": { "text": "The raiders break and scatter for the trees. The village will tell it taller every winter.", "effects": { "prestige": 8, "popularOpinion": 5 } },
      "failure": { "text": "They were harder men than you. You keep your life and little else.", "effects": { "health": -2, "gold": -6 } } },
    { "label": "Hide the family in the root cellar.", "effects": { "gold": -8 } },
    { "label": "Buy them off with bread and salt.", "require": { "goldMin": 10 }, "effects": { "gold": -10 } }
  ] },

{ "id": "got_red_comet", "title": "The Red Comet",
  "text": "A red sword hangs above the world, trailing fire across the sky night after night. Every septon, godi, and hedge-wizard in the land has an opinion.",
  "trigger": { "yearMin": 299, "chance": 0.9 },
  "once": true, "weight": 10,
  "options": [
    { "label": "It heralds glory for the bold.", "effects": { "prestige": 5 } },
    { "label": "It is a warning from {god}.", "effects": { "piety": 5 } },
    { "label": "It is a comet. They come and go.", "effects": { "skills": { "lea": 1 } } }
  ] },

{ "id": "got_old_nan", "title": "Old Nan’s Tales", "childhood": true,
  "text": "The oldest woman in the village pulls you close by the fire. ‘Now this is a story about the Long Night,’ she says, ‘when the sun hid its face for a generation, and the Others came riding on dead horses…’",
  "trigger": { "maxAge": 15, "chance": 0.3 },
  "weight": 6, "cooldown": 8,
  "options": [
    { "label": "Listen to every word.", "effects": { "skills": { "lea": 1 } } },
    { "label": "Scoff — then check the door twice.", "effects": { "skills": { "int": 1 } } },
    { "label": "Pray until you fall asleep.", "effects": { "piety": 2 } }
  ] },

{ "id": "got_wooden_swords", "title": "Wooden Swords", "childhood": true,
  "text": "The village children are playing at knights and raiders in the mud, with barrel staves for swords and a pot lid for the champion’s shield.",
  "trigger": { "maxAge": 15, "chance": 0.3 },
  "weight": 5, "cooldown": 8,
  "options": [
    { "label": "Fight for the pot lid.", "chance": 0.6,
      "success": { "text": "You come home muddy, bruised, and champion of the yard.", "effects": { "skills": { "mar": 1 } } },
      "failure": { "text": "A stave across the knuckles teaches its own lesson.", "effects": { "health": -1, "skills": { "mar": 1 } } } },
    { "label": "Watch how the winners move.", "effects": { "skills": { "lea": 1 } } }
  ] },

{ "id": "got_tourney", "title": "A Tourney Is Cried",
  "text": "Heralds cry a tourney — lists, a melee, and a purse of gold under silk pavilions. Half the district is going, from lords to pie-sellers.",
  "trigger": { "tierMin": 2, "chance": 0.2 },
  "weight": 5, "cooldown": 24,
  "options": [
    { "label": "Ride in the lists.", "chance": "battle",
      "success": { "text": "You keep your saddle to the last tilt and take the purse to the sound of your own name.", "effects": { "prestige": 15, "gold": 20 } },
      "failure": { "text": "The ground comes up fast. The crowd remembers the fall better than your name.", "effects": { "prestige": -5, "health": -1 } } },
    { "label": "Wager on the melee.", "chance": 0.5,
      "success": { "text": "Your man stands last on the field.", "effects": { "gold": 12 } },
      "failure": { "text": "Your man is carried from it.", "effects": { "gold": -8 } } },
    { "label": "Watch from the stands.", "effects": { "prestige": 1 } }
  ] },

{ "id": "got_hedge_knight", "title": "A Hedge Knight",
  "text": "A knight sleeps under your hedge — horse thin, mail patched, courtesy intact. He offers what he has for a hot meal: a strong arm and stories of half the realm.",
  "trigger": { "tierMax": 3, "chance": 0.18 },
  "weight": 5, "cooldown": 16,
  "options": [
    { "label": "Feed him, for the Warrior’s sake.", "effects": { "gold": -1, "piety": 3 } },
    { "label": "Spar with him at dawn.", "chance": 0.6,
      "success": { "text": "He shows you the guard that saved his life at Ashford.", "effects": { "skills": { "mar": 1 } } },
      "failure": { "text": "The flat of his sword finds your ribs — twice.", "effects": { "health": -1 } } },
    { "label": "Hear his stories of the wide realm.", "effects": { "skills": { "lea": 1 } } }
  ] },

{ "id": "got_maester", "title": "A Maester on the Road",
  "text": "A maester of the Citadel passes through, chain clinking — links of silver, iron, and Valyrian steel. For a modest consideration, his learning is yours.",
  "trigger": { "chance": 0.18 },
  "weight": 5, "cooldown": 16,
  "options": [
    { "label": "Have him physic the household.", "require": { "goldMin": 6 }, "effects": { "gold": -6, "health": 1 } },
    { "label": "Buy lessons in letters.", "require": { "goldMin": 10, "tierMax": 2 }, "effects": { "gold": -10, "addTrait": "literate" } },
    { "label": "Trade gossip of the great houses.", "effects": { "prestige": 1 } }
  ] },

{ "id": "got_weirwood", "title": "The Heart Tree",
  "text": "The weirwood’s carved face weeps red sap in the grove. The wind moves the blood-colored leaves, and for a moment it sounds like words.",
  "trigger": { "religionGroups": ["pagan"], "chance": 0.25 },
  "weight": 5, "cooldown": 8,
  "options": [
    { "label": "Kneel and pray as the First Men prayed.", "effects": { "piety": 6 } },
    { "label": "Sit vigil through the night.", "effects": { "piety": 3, "skills": { "lea": 1 } } },
    { "label": "Leave an offering at the roots.", "effects": { "gold": -2, "piety": 4 } }
  ] },

{ "id": "got_seven_blessings", "title": "Under the Seven-Pointed Star",
  "text": "The sept smells of incense and tallow. Seven altars, seven candles, seven blessings — and a septon who knows precisely how much your soul can afford.",
  "trigger": { "religionGroup": "christian", "chance": 0.25 },
  "weight": 5, "cooldown": 8,
  "options": [
    { "label": "Light candles to all Seven.", "effects": { "gold": -2, "piety": 6 } },
    { "label": "Sing with the septas.", "effects": { "piety": 3, "skills": { "dip": 1 } } },
    { "label": "Confess to the {holy}.", "effects": { "piety": 4, "opinion": { "role": "priest", "amt": 5 } } }
  ] },

{ "id": "got_drowned_ritual", "title": "What Is Dead May Never Die",
  "text": "A Drowned Man stands waist-deep in the cold surf, driftwood cudgel in hand, calling the faithful to be drowned for the Drowned God and pulled back gasping.",
  "trigger": { "cultures": ["ironborn"], "chance": 0.3 },
  "weight": 5, "cooldown": 16,
  "options": [
    { "label": "Be drowned anew.", "chance": 0.85,
      "success": { "text": "The sea takes you and gives you back. What is dead may never die.", "effects": { "piety": 10 } },
      "failure": { "text": "They pump the sea out of you on the shingle. You rise — but harder, not stronger.", "effects": { "health": -3, "piety": 4 } } },
    { "label": "Pay the priest to pray for your ship instead.", "effects": { "gold": -3, "piety": 4 } },
    { "label": "Refuse. The sea has had enough of you.", "effects": { "piety": -3 } }
  ] },

{ "id": "got_reaving", "title": "The Iron Price",
  "text": "A captain is fitting out longships and wants oars. The green lands are fat, the sea lanes are soft, and no ironborn ever grew rich planting turnips.",
  "trigger": { "cultures": ["ironborn"], "minAge": 16, "chance": 0.2 },
  "weight": 5, "cooldown": 16,
  "options": [
    { "label": "Take an oar.", "chance": "battle",
      "success": { "text": "You come home with salt in your beard and another man’s silver on your arm. Paid the iron price, every ounce.", "effects": { "gold": 18, "prestige": 8 } },
      "failure": { "text": "A fishing village with a stubborn holdfast. You leave two fingersbreadth of blood and take nothing.", "effects": { "health": -2 } } },
    { "label": "Stake coin in the venture.", "require": { "goldMin": 15 }, "chance": 0.6,
      "success": { "text": "The ships come home low in the water.", "effects": { "gold": 25 } },
      "failure": { "text": "The ships do not come home.", "effects": { "gold": -15 } } },
    { "label": "Stay ashore like a thrall.", "effects": { "piety": -2 } }
  ] },

{ "id": "got_dornish_harvest", "title": "Blood Oranges",
  "text": "The blood oranges are ripe, heavy and dark as bruises. Traders pole up the Greenblood for the pick of the crop.",
  "trigger": { "cultures": ["dornish"], "professions": ["farmer"], "seasons": [2], "chance": 0.3 },
  "weight": 5, "cooldown": 12,
  "options": [
    { "label": "Sell to the orphans of the Greenblood.", "effects": { "gold": 8 } },
    { "label": "Press sour red for the winesellers.", "effects": { "gold": 4, "prestige": 2 } },
    { "label": "Feast the village under the stars.", "effects": { "gold": -4, "popularOpinion": 6 } }
  ] },

{ "id": "got_kingsroad", "title": "Banners on the Kingsroad",
  "text": "A great lord’s party passes on the kingsroad — outriders, wheelhouse, a hundred servants, and a dust cloud you can taste from the fields.",
  "trigger": { "chance": 0.12 },
  "weight": 4, "cooldown": 12,
  "options": [
    { "label": "Sell provisions at travelers’ prices.", "require": { "professions": ["farmer", "merchant", "craftsman"] }, "effects": { "gold": 8 } },
    { "label": "Push forward and beg a boon.", "chance": 0.25,
      "success": { "text": "A ring of silver spins glittering from a gloved hand.", "effects": { "gold": 15 } },
      "failure": { "text": "An outrider’s whip clears the road, and you with it.", "effects": { "prestige": -3 } } },
    { "label": "Watch the banners go by.", "effects": { "prestige": 1 } }
  ] },

{ "id": "got_deserter", "title": "The Man Who Passes the Sentence",
  "text": "A deserter from the Night’s Watch has been taken on your land — ragged, wild-eyed, babbling of white shadows. The law of the North is older than the Wall: the sentence is death.",
  "trigger": { "cultures": ["northmen"], "tierMin": 3, "chance": 0.25 },
  "weight": 5, "cooldown": 16,
  "options": [
    { "label": "Swing the sword yourself.", "desc": "The man who passes the sentence should swing the sword.",
      "effects": { "prestige": 8, "popularOpinion": 5, "log": "{name} took off a deserter’s head with their own hand, in the old way." } },
    { "label": "Let the headsman earn his bread.", "effects": { "prestige": -2 } },
    { "label": "Send him back to the Wall in chains.", "effects": { "piety": 4, "prestige": -4 } }
  ] },

{ "id": "got_rhllor_priest", "title": "The Red Priest",
  "text": "At the crossroads a red priest feeds a nightfire, preaching in accented Common of R’hllor, the Lord of Light, and of a darkness that is coming for every living thing.",
  "trigger": { "chance": 0.08 },
  "weight": 4, "cooldown": 30,
  "options": [
    { "label": "Stare into the flames.", "chance": 0.3,
      "success": { "text": "For half a heartbeat you see towers of ice, and eyes as blue as death. Then only fire.", "effects": { "skills": { "int": 1 } } },
      "failure": { "text": "You see burning wood. The priest looks disappointed on your behalf.", "effects": {} } },
    { "label": "Hear the foreign creed out.", "effects": { "skills": { "lea": 1 } } },
    { "label": "Keep to the gods of your fathers.", "effects": { "piety": 3 } }
  ] },

{ "id": "got_mance_rumor", "title": "The King-Beyond-the-Wall",
  "text": "Traders from the Wall bring word: the free folk are gathering. A deserter crow named Mance Rayder is stitching the raiding clans into a host and calling himself King-Beyond-the-Wall.",
  "trigger": { "yearMin": 298, "cultures": ["northmen", "free_folk"], "chance": 0.5 },
  "once": true, "weight": 7,
  "options": [
    { "label": "Sharpen the axes.", "effects": { "skills": { "mar": 1 } } },
    { "label": "Pray the Wall holds, as it always has.", "effects": { "piety": 3 } }
  ] },

{ "id": "got_white_raven", "title": "The White Raven",
  "text": "A white raven has come from the Citadel: summer is over. The oldest voices in the village say the same thing, quietly — this one will be long.",
  "trigger": { "seasons": [3], "chance": 0.3 },
  "weight": 4, "cooldown": 30,
  "options": [
    { "label": "Lay in stores against the cold.", "require": { "goldMin": 6 }, "effects": { "gold": -6, "health": 1 } },
    { "label": "Share what you have. Winter makes neighbors kin.", "require": { "goldMin": 10 }, "effects": { "gold": -10, "popularOpinion": 8, "piety": 3 } },
    { "label": "Winter is coming. It always is.", "effects": {} }
  ] },

{ "id": "got_greyscale", "title": "A Grey Patch",
  "text": "There is a patch of grey, cracked skin on your child’s arm, stiff and cold to the touch. You have heard the word all your life, always about someone else’s child: greyscale.",
  "trigger": { "hasYoungChild": true, "chance": 0.07 },
  "weight": 4, "cooldown": 40,
  "options": [
    { "label": "Send for a maester, whatever it costs.", "require": { "goldMin": 10 }, "chance": 0.85,
      "success": { "text": "The maester scrapes, salves, and at last smiles: scald-rash, not the grey death. The household breathes again.", "effects": { "gold": -10 } },
      "failure": { "text": "The maester’s face tells you before his words do. The grey climbs, and nothing in his chain can stop it.", "effects": { "gold": -10, "killChild": true } } },
    { "label": "Pray, and bathe the arm in blessed water.", "chance": 0.6,
      "success": { "text": "Whether it was the prayers or the scrubbing, the grey fades. You give thanks on your knees.", "effects": { "piety": 5 } },
      "failure": { "text": "The gods are silent. The stone spreads.", "effects": { "killChild": true } } },
    { "label": "Pay the hedge-witch for her simples.", "chance": 0.7,
      "success": { "text": "Foul-smelling poultices, a week of fear — and clean pink skin beneath.", "effects": { "gold": -4 } },
      "failure": { "text": "Her simples fail. Some things are beyond herbs.", "effects": { "gold": -4, "killChild": true } } }
  ] }

]
}
});
