'use strict';
const { dependsOnRuntime } = require('../support/runtime-dependencies');
dependsOnRuntime(__filename, [
  'js/settlement.js',
  'data/settlements.js',
  'data/settlements_real.js'
]);

/* Real-world settlement fill (data/settlements_real.js, generated by
   tools/settlement_import.py from the GeoNames database): the fill presentations
   append after the curated layouts, replace generated names/locations without
   forcing early visibility, and stay inside the compiled slot contract.
   NOT run by the authoring agent (owner runs the harness). */

const { test, expect } = require('../support/fixture');
const { openGame } = require('../support/game/navigation');
const { startDeterministicGame } = require('../support/game/start');

test('real fill appends valid presentations after the curated layouts in both bookmarks',
  async function ({ page }, testInfo) {
    await openGame(page, testInfo);

    const result = await page.evaluate(function () {
      const out = { overCap:[], dupNames:[], missingSites:[], badFill:[],
        headMismatch:[], fillCounties:0, fillEntries:0, curatedFirst:[] };
      for (const bm of ['867', '1066']) {
        for (const pr of FB.bookmark(bm).provinces) {
          if (!pr.settlements || !pr.settlements.length) continue;
          if (pr.settlements.length > 8) out.overCap.push(bm + ':' + pr.id);
          const names = {};
          let firstFill = -1;
          for (let i = 0; i < pr.settlements.length; i++) {
            const e = pr.settlements[i];
            if (names[e.name]) out.dupNames.push(bm + ':' + pr.id + ':' + e.name);
            names[e.name] = 1;
            if (!FBDATA.settlementSites[e.site]) {
              out.missingSites.push(bm + ':' + pr.id + ':' + e.site);
            }
            if (e.fill) {
              if (e.kind !== 'village') out.badFill.push(bm + ':' + pr.id + ':' + e.site);
              if (firstFill < 0) firstFill = i;
              out.fillEntries++;
            }
          }
          if (firstFill > 0) {
            /* fill never inserts ahead of curated slots */
            for (let i = firstFill + 1; i < pr.settlements.length; i++) {
              if (!pr.settlements[i].fill) out.curatedFirst.push(bm + ':' + pr.id);
            }
          } else if (firstFill === 0) {
            /* counties with no curated list gain a county-name head */
            if (pr.settlements[0].name !== pr.name) {
              out.headMismatch.push(bm + ':' + pr.id + ':' + pr.settlements[0].name);
            }
            out.fillCounties++;
          }
        }
      }
      return out;
    });

    expect(result.overCap).toEqual([]);
    expect(result.dupNames).toEqual([]);
    expect(result.missingSites).toEqual([]);
    expect(result.badFill).toEqual([]);
    expect(result.headMismatch).toEqual([]);
    expect(result.curatedFirst).toEqual([]);
    /* the import covers the overwhelming majority of counties */
    expect(result.fillCounties).toBeGreaterThan(250);
    expect(result.fillEntries).toBeGreaterThan(1500);
  });

test('no settlement name carries a modern numbered administrative label',
  async function ({ page }, testInfo) {
    await openGame(page, testInfo);

    const result = await page.evaluate(function () {
      /* 'Paris 16 Passy'-style GeoNames labels are cleaned to their
         historical reading ('Passy') at import; bare numeric labels are
         dropped. Neither the data nor the compiled world may keep one. */
      const numbered = [];
      for (const bm of ['867', '1066']) {
        for (const pr of FB.bookmark(bm).provinces) {
          for (const e of (pr.settlements || [])) {
            if (/\d/.test(e.name)) numbered.push(bm + ':' + pr.id + ':' + e.name);
          }
        }
      }
      return { numbered:numbered };
    });

    expect(result.numbered).toEqual([]);
  });

test('fill names use the attested period name, not the modern one',
  async function ({ page }, testInfo) {
    await openGame(page, testInfo);

    const result = await page.evaluate(function () {
      /* The importer substitutes a documented medieval identity when there
         is one and drops modern-only candidates so another real place fills
         the slot. Spot-check both policies across the map. */
      const modern = ['Tel Aviv', 'Ankara', 'İzmir', 'Clermont-Ferrand',
        'Casablanca', 'Kaliningrad', 'Trabzon', 'Şanlıurfa',
        'Milton Keynes', 'Bletchley', 'Wolfsburg', 'Bremerhaven',
        'Wilhelmshaven', 'Glenrothes', 'Telford', 'Bingöl', 'Tampere',
        'Kędzierzyn-Koźle', 'Küçükçekmece', 'Makhachkala', 'Mikkeli',
        'Novorossiysk', 'Saratov', 'Savonlinna', 'Sevastopol', 'Simferopol',
        'Vaasa', 'Vantaa', 'Anapa', 'Gatchina', 'Yevpatoriya'];
      const rejected = ['Aprilia', 'Ar Rayyan', 'Arak', 'Bandar Abbas',
        'Carbonia', 'Dammam', 'Doha', 'Dushanbe', 'Esbjerg', 'Fredrikstad',
        'Halle-Neustadt', 'Helsinki', 'Jyväskylä', 'Karabük', 'Karlskrona',
        'Kenitra', 'Khorramshahr', 'Kırıkkale', 'Kristiansand', 'Kuopio',
        'Latina', 'Lorient', 'Ludwigshafen am Rhein', 'Madinat an Nasr',
        'Netanya', 'Newtownabbey', 'Osmaniye', 'Petah Tiqva', 'Port Said',
        'Ramadi', 'Rishon LeTsiyyon', 'Shahin Shahr', 'Shannon',
        'Sidi Bel Abbes', 'Sundsvall', 'Tolyatti', 'Zahedan',
        'Bournemouth', 'Donetsk', 'Khartoum', 'Lusail', 'Saint Petersburg',
        'Zagazig', 'Bağcılar', 'Ciudad Lineal', 'Dniprovskyi',
        'East Helsinki', 'Põhja-Tallinn', 'Rostov-on-Don', 'Volgograd',
        'Joensuu', 'Kronstadt', 'Shakhty', 'Shevchenkivskyi', 'Volgodonsk'];
      const period = ['Jaffa', 'Ancyra', 'Smyrna', 'Clermont', 'Anfa',
        'Königsberg', 'Trebizond', 'Edessa', 'Bicchelai', 'Hesslingen',
        'Geestendorf', 'Heppens', 'Markinch', 'Dawley', 'Çapakçur', 'Koski',
        'Koźle', 'Rhegion', 'Tarki', 'Savilahti', 'Bata', 'Tana', 'Uvek',
        'Olavinlinna', 'Chersonesus', 'Scythian Neapolis', 'Korsholm',
        'Helsinge', 'Mapa', 'Khotchino', 'Gözleve'];
      const seenModern = [], seenRejected = [], seenPeriod = {};
      const bicchelaiSites = {};
      for (const bm of ['867', '1066']) {
        for (const pr of FB.bookmark(bm).provinces) {
          for (let i = 0; i < (pr.settlements || []).length; i++) {
            const site = pr.settlements[i];
            const name = site.name;
            if (modern.indexOf(name) >= 0) seenModern.push(bm + ':' + pr.id + ':' + name);
            if (rejected.indexOf(name) >= 0) seenRejected.push(bm + ':' + pr.id + ':' + name);
            if (period.indexOf(name) >= 0) seenPeriod[name] = 1;
            if (name === 'Bicchelai') bicchelaiSites[pr.id + ':' + site.id] = 1;
          }
        }
      }
      /* a period name the curated county head already carries never appears
         as a fill entry (the import dedups it), so only require the ones
         with no curated head */
      return { seenModern: seenModern, seenRejected: seenRejected,
        jaffa: !!seenPeriod['Jaffa'], smyrna: !!seenPeriod['Smyrna'],
        clermont: !!seenPeriod['Clermont'], anfa: !!seenPeriod['Anfa'],
        konigsberg: !!seenPeriod['Königsberg'],
        bicchelaiSites: Object.keys(bicchelaiSites).length,
        hesslingen: !!seenPeriod['Hesslingen'],
        geestendorf: !!seenPeriod['Geestendorf'],
        uvek: !!seenPeriod['Uvek'],
        chersonesus: !!seenPeriod['Chersonesus'],
        korsholm: !!seenPeriod['Korsholm'] };
    });

    expect(result.seenModern).toEqual([]);
    expect(result.seenRejected).toEqual([]);
    expect(result.jaffa).toBe(true);
    expect(result.smyrna).toBe(true);
    expect(result.clermont).toBe(true);
    expect(result.anfa).toBe(true);
    expect(result.konigsberg).toBe(true);
    expect(result.bicchelaiSites).toBe(1);
    expect(result.hesslingen).toBe(true);
    expect(result.geestendorf).toBe(true);
    expect(result.uvek).toBe(true);
    expect(result.chersonesus).toBe(true);
    expect(result.korsholm).toBe(true);
  });

test('fill presentations do not force early settlement visibility', async function ({ page }, testInfo) {
    test.skip(testInfo.project.name !== 'chromium-file',
      'The visibility contract runs once against the primary file target.');
    await openGame(page, testInfo);
    await startDeterministicGame(page);

    const result = await page.evaluate(function () {
      const pr = FB.world.provs.find(function (p) {
        const info = FB.world.sitesByProv[p.id];
        return !p.wasteland && p.dev0 <= 2 && info && info.authored === 0 &&
          info.list.length >= info.legacyBase + 1;
      });
      if (!pr) return { found:false };
      const info = FB.world.sitesByProv[pr.id];
      return {
        found:true,
        pid:pr.id,
        authored:info.authored,
        visible:FB.settlementVisibleCount(FB.state, pr.id),
        legacyBase:info.legacyBase,
        headName:info.list[0].name,
        countyName:pr.name,
        headAuthored:info.list[0].authored,
        hiddenName:info.list[info.legacyBase].name,
        hiddenVisible:FB.siteVisible(FB.state, info.list[info.legacyBase]),
        paris:FB.world.sitesByProv.paris.list[0].name,
        parisAuthored:FB.world.sitesByProv.paris.authored
      };
    });

    expect(result.found).toBe(true);
    /* a pure-fill county compiles with no visibility-forcing authored count */
    expect(result.authored).toBe(0);
    expect(result.visible).toBe(result.legacyBase);
    /* its head settlement is the county's real name, not a generated one */
    expect(result.headName).toBe(result.countyName);
    expect(result.headAuthored).toBe(true);
    /* slots beyond the baseline stay hidden until development reveals them */
    expect(result.hiddenVisible).toBe(false);
    /* curated layouts keep their visibility-forcing authored count */
    expect(result.paris).toBe('Paris');
    expect(result.parisAuthored).toBe(1);
  });
